name: Release Docker Image
on: 
  release:
    types: 
      - published

jobs:

  release:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Get version without v character
        id: version
        run: |
          VERSION=${{github.event.release.tag_name}}
          VERSION_WITHOUT_V=${VERSION:1}
          echo "value=${VERSION_WITHOUT_V}" >> $GITHUB_OUTPUT
      - name: Release to Docker
        run: | 
          echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          npm run docker:build
          docker tag asyncapi/github-action-for-cli:latest asyncapi/github-action-for-cli:${{ steps.version.outputs.value }}
          docker push asyncapi/github-action-for-cli:${{ steps.version.outputs.value }}
          docker push asyncapi/github-action-for-cli:latest